### ISSUE TITLE
Autosplitter Splitting Twice

### ISSUE THREAD

**Issue by xCrunk** [Eein/octopath-autosplitter#25]
The splits are occurring twice in a row. Quick example is once I defeat Helgenish (for Primrose single story route) and it ends the split, the next split (Russell) is also ended.

**Comment by Eein** [comment]
(Updated for documentation in case people run into the same issue)

It looks like this occurs when the autosplitter is loaded through the splits editor AND the component (or two components are loaded) - better to just remove the component and use the autosplitter activation in the splits editor
