### ISSUE TITLE
splits reset when hitting continue

### ISSUE THREAD

**Issue by Eein** [Eein/octopath-autosplitter#27]
https://www.twitch.tv/videos/1459400848

Not really able to replicate... just freak occurence that just so happened to explode the timer...

**Comment by Eein** [comment]
https://www.twitch.tv/videos/1459400848

**Comment by Eein** [comment]
if we can track a value thats consistent on the character select screen it might be easier to ensure this doesnt happen...

**Comment by ak505188** [comment]
Got another occurance of this https://clips.twitch.tv/BigCoweringChinchillaANELE-db4UHY1LDkN7nSjh
